leftnav:
- identifier: ee238062-35d3-4595-a28a-7e4c33966ccd
  name: Marguerite de Navarre Society Website
  pageRef: /external-resources/marguerite-de-navarre-society-website_ee238062-35d3-4595-a28a-7e4c33966ccd
  weight: 10
